### PR TITLE
Adding test and example for Resizing with Segmentation Maps

### PR DESCRIPTION
**Pull request by ariG23498**
The end result of the `example`:

image

### CODE REVIEW

**Comment by cosmo3769** [comment]
Thanks for the PR!

In the [PR](https://github.com/keras-team/keras-cv/pull/1834), Ian also mentioned about one more place to update the test case, in `with_segmentation_masks_test.py`: [comment](https://github.com/keras-team/keras-cv/pull/1834#pullrequestreview-1449815737)

**Comment by cosmo3769** [comment]
Also, The output looks good. But can we show something like this way: One sample each with different resize method in one visualization:

* _resize_with_crop
* _resize_with_pad
* _resize_with_distortion

**Comment by ariG23498** [comment]
I have made a defiberate casting in the `tf.image.pad_to_bounding_box` method. The deliberate casting is due to an error (please refer to the this [gist](https://colab.research.google.com/gist/ariG23498/5d8049c7ac69da6f470761f094509496/scratchpad.ipynb) for the error)

**Comment by ariG23498** [comment]
# Resize
image

# Crop
image

# Pad
image

**Pull request merged**
